name: gitt
description: CLI tool to do git things
repository: https://github.com/rIIh/gitt-dart
version: 1.0.3

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  interact_cli: ^2.3.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  gitt:
